portier/portier-broker

README.rst, src/config.rs, src/email.rs
This is useful when testing locally with [MailHog], for example.
[MailHog]: https://github.com/mailhog/MailHog
=> Configurable SMTP host.

src/email.rs, src/lib.rs.in, src/oidc.rs
See https://github.com/onli/sinatra-browserid/commit/1dc22b29c15304db34b041ab0be01eeaa2ae322d for example usage
=> add RP nonce

src/lib.rs.in
=> Add back `email::request` call.

src/lib.rs.in, src/main.rs
This is an attempt at fixing the routing related TODO in `main.rs`. Not sure if this is something we want, just throwing it out there. Low prio, in any case.
(Probably easier to review with `?w=1` / `-w`)
=> Add a macro to simplify route handler functions.

src/crypto.rs, src/lib.rs, src/oidc.rs, src/store_cache.rs
These changes were made after feedback on the feat/error-handling branch, but were missing because I botched the last rebase when switching machines. :/
=> Missing feedback changes from feat/error-handling.

README.rst, config.toml.dist, src/config.rs, src/crypto.rs, src/email.rs, src/lib.rs, src/main.rs, src/oidc.rs, src/serde_types.in.rs
Supersedes #48.
I believe all of the commits are sane and sufficiently granular to satisfy the reviews on the former.
=> Configuration overhaul (support environment variables)

src/lib.rs
06402d7 is a small breaking change, but one I believe we need to do for better spec compliance.
=> Add validations and fix redirect params.

clippy.toml, src/config.rs, src/crypto.rs, src/lib.rs, src/oidc.rs
Nothing earth-shaking here, just some superfluous closures and borrows.
=> Address linter warnings from Clippy

README.rst, src/config.rs, src/crypto.rs, src/main.rs, src/serde_types.in.rs
I think this is the last blocker for getting us cleanly onto Heroku.
=> Support specifying keys as literal PEM strings, make config file optional

src/lib.rs, src/main.rs
Identical to #87, but with HSTS not set to include subdomains.
Fixes #85 
Fixes #38
=> Implement middleware and security headers

Cargo.lock, Cargo.toml, src/lib.rs, src/main.rs, static/forward.js, static/style.css, tmpl/confirm_email.mustache, tmpl/email_html.mustache, tmpl/email_text.mustache, tmpl/error.mustache, tmpl/forward.mustache
@onli wants to add some work to this. This also fixes #90.
=> Add some styling

README.rst, config.toml.dist
I've made some fixes for readability.
=> Various documentation fixes.

tmpl/email_html.mustache, tmpl/email_text.mustache
This puts the code on its own line, makes it monospace and larger.
=> Improve email code readability.

src/handlers/oidc.rs
=> Lowercase the domain when deciding which flow to follow

src/oidc_bridge.rs
=> Lowercase domains when looking up provider info

build.rs, src/config.rs, src/crypto.rs, src/email_bridge.rs, src/error.rs, src/handlers/email.rs, src/handlers/mod.rs, src/handlers/oauth2.rs, src/handlers/oidc.rs, src/lib.rs, src/main.rs, src/oidc_bridge.rs, src/store.rs, src/store_cache.rs, src/validation.rs
Still not perfect -- we can still panic in a bunch of places -- but at least this ensures we leave behind sane error messages.
Fixes #56
=> Replace unwrap() with expect() or proper handling

README.rst, config.toml.dist, src/config.rs, src/handlers/oidc.rs, src/lib.rs, src/oidc_bridge.rs, src/serde_types.in.rs, src/store.rs, src/store_cache.rs, src/store_limits.rs
Fixes: #70
Replaces: #109 #114
=> Implement SMTP ratelimit

.travis.yml, src/oidc_bridge.rs, src/store_limits.rs
=> Use Travis to report on code coverage and clippy lints

build-docker.sh
I neglected to actually test the Docker build after #124. :/
=> Fix gettext missing from Docker build.

Cargo.lock, Cargo.toml, src/store.rs
=> Fix expired

lang/en.po, res/static/style.css, src/config.rs, src/handlers/auth.rs, tmpl/login_hint.mustache
=> prompt for login_hint if it wasn't presented

src/crypto.rs
=> return verified_email as a bool (true) per oidc recommendations

app.json
Should fix https://github.com/portier/portier.github.io/issues/40
=> Pin Heroku stack to heroku-16 for now.

src/agents/key_manager/manual.rs, src/agents/key_manager/rotating.rs, src/agents/store/redis.rs, src/agents/store/rusqlite.rs, src/bridges/email.rs, src/bridges/oidc.rs, src/config/env.rs, src/config/mod.rs, src/crypto.rs, src/email_address.rs, src/macros.rs, src/main.rs, src/utils/delay_queue_task.rs, src/utils/keys.rs, src/utils/pem.rs, src/web.rs
=> Enable hints from `clippy:pedantic`.

Cargo.lock, src/agents/key_manager/manual.rs, src/agents/store/redis.rs, src/email_address.rs, src/handlers/auth.rs, src/utils/redis/pubsub.rs, tests/e2e/package.json, tests/e2e/src/broker.ts, tests/e2e/yarn.lock
=> Minor upgrades to dependencies

src/utils/redis/pubsub.rs
Should fix #234.
Turns out a fresh combine `Decoder` for every `read()` no longer works, we need to preserve it. Appears to have fixed it locally on my Mac.
=> Preserve combine decoder instance in pubsub

config.toml.dist, src/agents/fetch.rs, src/agents/mailer/mailgun.rs, src/agents/mailer/postmark.rs, src/agents/mailer/sendgrid.rs, src/agents/store/mod.rs, src/bridges/email.rs, src/bridges/oidc.rs, src/config/env.rs, src/config/mod.rs, src/config/toml.rs, src/handlers/auth.rs, src/webfinger.rs
So we can ignore our automated tests.
=> Ignore specific emails in metrics

src/bridges/email.rs, src/bridges/oidc.rs
I suspect the `portier_auth_{email,oidc}_requests` counters are incorrect and double-counting some requests. This changes the counter so it is only incremented after session save.
=> Fix bridge request counters

src/agents/mailer/mailgun.rs, src/agents/mailer/mod.rs, src/agents/mailer/postmark.rs, src/agents/mailer/sendgrid.rs
Via https://serverfault.com/a/56481
=> Add a List-Id header to prevent autoresponders
