Cargo.toml, src/main.rs
The `d.version(Some(VERSION.to_string()))` function automatically implements handling `--version`, and takes an `Option<String>`, so we have to convert `VERSION`, a `&'static str` before passing it.
=> Docopt round 2

README.rst, src/config.rs, src/email.rs, src/error.rs, src/lib.rs.in, src/oidc.rs, src/store.rs, src/store_cache.rs, test.json
Fixes #6 and #7.
Note that these are still babysteps in Rust for me. Beside that, some things I'm considering:
- Maybe we should have `fetch_json_cached` be a store method. Seems like a slightly better place to handle this sort of thing than in oidc.
- Minimum cache age is now not configurable. Simplest would be using `expire_keys`, but it seems weird to tie it to session lifespan. I'm itching to rename `expire_keys`, actually, and then we can have `session_age`, `min_cache_age`, and `max_cache_size` in the future. But I'm not sure what our view is on breaking changes?
=> Cache GET requests to OpenID providers.

src/lib.rs.in, src/main.rs
Required as per OAuth2: https://tools.ietf.org/html/rfc6749#section-3.1
See discussion in #13
=> Add support for `GET /auth`

src/crypto.rs, src/email.rs, src/error.rs, src/lib.rs, src/oidc.rs, src/store.rs, src/store_cache.rs
This PR adds error handling to all runtime situations where errors can be raised. The remaining unwraps are either possible startup failures, or cases where we always expect success given in those conditions / given a correct environment.
I've added a TODO for categorising errors that we should report back to the user. Right now, errors are either propagated from libs or `BrokerError::Custom`, and these all result in a log entry and a 503 to the user. The exception is missing request parameters, which send a 400 with a description.
I'll continue working on proper notification to the user, but created this PR so that I can get some review up to this point, as the changes are already quite substantial. (But hopefully the commits are clear steps.) IMHO, we can also merge up to this point; it …
=> Handle run-time errors

build-docker.sh
Using this script, I've pushed a first experimental image to [portier/broker](https://hub.docker.com/r/portier/broker/). The image is ~3MB compressed, and ~7MB extracted on disk.
I've tested that the oidc flow is able to communicatie over HTTPS with Google.
If we merge this, I can for now configure a private Jenkins instance to poll `master` every 15 minutes and build images. (The current image was also produced on this Jenkins instance.)
=> Add a script to build Docker images.

Cargo.toml
We should change this dep to 0.3.1 once that's released.
See: https://crates.io/crates/emailaddress
=> Prevent panic on invalid email address. Fixes #28

README.rst, config.toml.dist, src/config.rs, src/email.rs, src/serde_types.in.rs
Part of #43. The other part I want to implement is the TLS security level, but that depends on a lettre patch.
I've verified this works at least with Amazon SES.
=> Allow setting SMTP credentials.

build-docker.sh
It should be possible to configure the container entirely through env
vars now. This also allows changing the location of config.
=> Remove default config file from Docker image.

.github/ISSUE_TEMPLATE.md
This makes it more obvious where to go if you're trying to file a security bug.
=> Add a new issue template

README.rst, config.toml.dist, src/config.rs, src/lib.rs, src/serde_types.in.rs
As per discussion in #45.
I went with a bit more extended configuration, because it felt more natural. This matches the config we have for providers. The alternative, I think, would've been a flat list `redirect_uris`, but it'd be a toplevel field in the config.
=> Optional whitelist of clients.

src/oidc.rs
This reverts commit 3d6d378be4a25c64e701e061809bee60d2af86fc.
The Google consent screen uses scary language:
=> Revert "Require consent for oidc flow."

static/style.css, tmpl/confirm_email.mustache
The important message is not the form, but that an email was sent. This minor styling change tries to support that by making the form elements smaller and adding a styled hr, also html semantics.
=> Seperate form login from primary message

src/lib.rs, src/main.rs, src/middleware/headers.rs, src/middleware/logging.rs, src/middleware/mod.rs, src/middleware/origin.rs
This pull request:
- Extracts middleware out of `lib.rs` and into its own module hierarchy.
- Refactors and adds basic unit tests for our security headers middleware.
- Introduces a new middleware to redirect incoming requests to the broker's canonical origin, as derived from `public_url`, which fixes #83.
=> Middleware refactor and canonical origin enforcement

res/static/style.css, src/email_bridge.rs, tmpl/confirm_email.mustache
Implementation of 12 character codes from z-base-32, as discussed in #69.
This also ignores case and any other input outside the character set.
=> Implement OTP using 12 chars of z-base-32.

tmpl/confirm_email.mustache
Note the space between the input widget and the submit button
---
=> Prevent whitespace from breaking template layout

.travis.yml
This reverts commit 437203001508c7ea1c46a54d1340eb4e491ac5b7.
At least, I think this should work. Let's see what Travis says.
=> No longer need to pin clippy with v0.0.104.

.gitignore, Cargo.lock, Cargo.toml, build-docker.sh, build.rs, lang/de.po, lang/en.po, lang/nl.po, src/config.rs, src/email_bridge.rs, src/handlers/oidc.rs, src/lib.rs, tmpl/confirm_email.mustache, tmpl/email_html.mustache
See the discussion in #116.
This implements i18n via gettext, using the rust gettext module from https://github.com/justinas/gettext. A simple makefile is provided to help create the .mo files which the program reads. Translations are given as variables into the templates, but are strings in the sourcecode – that is not perfect, but https://github.com/nickel-org/rust-mustache does not support the better approach of calling a function from within the template.
I tested this till the point of sending the email out.
=> Support for i18n

res/static/fragment_callback.js, src/config.rs, src/crypto.rs, src/email_bridge.rs, src/handlers/oauth2.rs, src/main.rs, src/oidc_bridge.rs, tmpl/forward.mustache, tmpl/fragment_callback.mustache
Alternative to #84. See also the discussion in #85.
When using the implicit flow with Google, there is apparently never a prompt, not even on the first login. Perhaps that's because we already provide a `login_hint` as well.
We're also never listed in 'connected apps' in Google settings, because we don't have an access token. That's pretty good too. (However, if we want to send `prompt=consent` in the future, we _do_ get listed, and we _do_ get scary warnings the second login and beyond, like in #80. Maybe there are more options to control that.)
Google doesn't support `response_mode=form_post`, so we add a small page inbetween to capture the fragment parameters and POST them to us.
This removes a roundtrip on the server side, but adds a roundtrip on the client side. However, this also …
=> Implement implicit flow for Google.

Cargo.lock, Cargo.toml, README.rst, config.toml.dist, src/config.rs, src/handlers/mod.rs, src/handlers/oidc.rs, src/main.rs, src/middleware/headers.rs, src/middleware/mod.rs, src/serde_types.in.rs
Fixes #41.
The approach here is to just set `Cache-Control: no-cache, no-store` for everything, except when overridden explicitly. The overrides are for static files, discovery and keys, each having a config var.
The discovery and keys resources don't set Last-Modified and Etag. I feel like it's more trouble than it's worth?
=> Add cache headers.

Aptfile
I've added the `https://github.com/heroku/heroku-buildpack-apt` buildpack and used this to do a deploy on Heroku. So this is already running and working on the public broker!
=> Add the apt buildpack so Heroku can build i18n

Cargo.lock, Cargo.toml, lang/de.po, lang/en.po, lang/nl.po, src/bridges/email.rs, src/bridges/oidc.rs, src/crypto.rs, src/error.rs, src/handlers/auth.rs, src/handlers/pages.rs, src/http.rs, src/macros.rs, src/store.rs, tmpl/error.mustache
This PR is on top of #149.
There are a bunch of changes to error handling here:
- I've added `BrokerError::SessionExpired`, because I expect it to be a very common case, for which we can now give better feedback. The other classes of `BrokerError::Input` are all integration issues, and can use the generic template.
- I've added `BrokerError::ProviderInput`, which covers some of the previous cases for `BrokerError::Provider` and `BrokerError::Input`. This is specifically for errors related to the request input (thus 400), not provider communication (still 503). All `BrokerError::Input` is now related to the RP, while all `BrokerError::Provider*` is related to the provider. Error messages reflect this.
- Internal errors and rate limiting now no longer redirect back to the RP, and always …
=> Improve error messages and user feedback.

src/bridges/oidc.rs
Looks like Google includes it, so that's one less difference between RP-side and IdP-side protocol.
=> Verify iat claim from IdP / Google

src/handlers/auth.rs
Reflects this spec: https://github.com/portier/portier.github.io/pull/33
Notably, stop announcing `email_verified`, because we have been setting it incorrectly all this time, and probably want to rid ourselves of it.
Also drops `sub`, which duplicates `email` in our case. This also brings things in line with the IdP side.
I figure we shouldn't add `email_original`, because it's unofficial. Apparently, nobody announces `nonce` either, so it is omitted here as well.
These are still present in the token, we just stop announcing them in config.
=> Adjust supported claims to mirror spec

src/bridges/email.rs, src/bridges/mod.rs, src/handlers/auth.rs, src/http.rs
This allows the RP to have the token returned as a fragment parameter, e.g.: `#id_token=aaabbbccc`
Can be tested with the demo RP by commenting this line: https://github.com/portier/demo-rp/blob/6aee99fe126eceda527cae1f6da3f02a68401b6e/server.py#L95
This will break it, but allows inspecting the result in the browser.
The code also keeps existing parameters intact. For example, on line 97, change `'/verify'` to `'/verify#foo=3&bar=2'`. Portier will redirect to `/verify#foo=3&bar=2&id_token=aaabbbccc`.
=> Implement response_mode=fragment

src/bridges/oidc.rs
If the IdP supported this, it eliminates a broker roundtrip, which is nice.
Previous, the steps were:
- IdP sends 303 redirect response
- Broker translates fragment to form_post
- Broker handles POST request
Now, it's just:
- IdP sends a form response that submits to broker
- Broker handles POST request 
Also changes the way we build the IdP auth url to use the `url` crate serializer. One less error scenario.
=> Request IdP response_mode=form_post if supported

src/bridges/mod.rs, src/handlers/auth.rs, src/http.rs
Return the `state` back to the initiator when returning the `id_token`. Fixes #170.
=> pass the 'state' parameter back in the implicit flow

src/email_address.rs
Update the broker implementation to match the spec changes in https://github.com/portier/portier.github.io/pull/38
=> Use the last occurence of @ in email normalization

lang/de.po, lang/en.po, lang/nl.po, src/handlers/auth.rs, src/http.rs, tmpl/login_hint.mustache
I apparently never created a PR for these fixes I had lying around locally. These are for the form displayed when no `login_hint` is provided.
@onli Maybe you can also add the two missing German translations?
=> Fixes for the login form

src/handlers/auth.rs, tests/e2e/main.js, tests/e2e/src/relying-party.js, tests/e2e/src/tests.js
This makes it so `openid` is required, and `email` is optional, but provided in the id_token claims regardless. Any other unknown scopes result in an error.
=> Validate `scope`, fixes #180

.github/workflows/build.yml, Cargo.lock, Cargo.toml, src/bridges/email.rs, src/bridges/mod.rs, src/bridges/oidc.rs, src/error.rs, src/handlers/auth.rs, src/web.rs
This adds JSON responses, and I believe should be enough to fix #198. I don't believe this adds any additional security concern; no new information is exposed or made accessible compared to the regular HTML responses.
A notable dependency update is Lettre. The 0.9.3 release should fix error messages.
Another notable change is that we attach build products to each CI run. We'll have debug binaries for all platforms for every push.
=> Various fixes, add JSON responses

.github/workflows/build.yml, docs/build.md, tests/e2e/src/relying-party.js, tests/e2e/src/tests.js, tests/e2e/yarn.lock
Hopefully, setting a minimum Rust will help downstream packaging in the future, where we may have to rely on whatever Rust version is packaged. We'll probably bump often and not be far behind stable in terms of support, but at least we can indicate something this way.
Was hoping we could go down to 1.40, but that fails on portier-broker itself. I'm also curious how our dependencies will fare going forward.
=> Test Safari in CI, set minimum supported Rust to 1.41

tests/e2e/main.ts, tests/e2e/package.json, tests/e2e/src/broker.ts, tests/e2e/src/env.ts, tests/e2e/src/mailbox.ts, tests/e2e/src/relying-party.ts, tests/e2e/src/tests.ts, tests/e2e/tsconfig.json
This PR converts the E2E tests to TypeScript, to be consistent with `portier-node`.
(If this warning is present, this PR depends on https://github.com/portier/portier-node/pull/9. Until that's merged and released on npm, CI likely won't pass since TypeScript is going to fail to compile.)
- Converted CommonJS imports/exports to ES6
- Added new `npm run test:chrome` and `npm run test:firefox` scripts to make it easier to run browser tests on Windows
- Converted all files to TypeScript
- Updated files to match output from latest version of Prettier
=> Convert E2E tests to TypeScript

src/agents/mailer/postmark.rs, src/config/env.rs, src/config/mod.rs, tests/e2e/package.json, tests/e2e/src/broker.ts, tests/e2e/src/http-mailer.ts, tests/e2e/src/main.ts, tests/e2e/src/tests.ts
This PR adds support for testing the HTTP requests sent to HTTP mailers as part of the JavaScript E2E tests.
Based on the suggestions from @stephank, I added a new config option `BROKER_POSTMARK_API`, which is undocumented as it's only intended to be used during tests. The value of this environment variable is used as the endpoint where the postmark mailer sends HTTP requests. If not specified, it defaults to Postmark's API.
I've also added a new test utility, `postmarkTest`, that only runs the test when `TEST_MAILER` is equal to `postmark`.
The approached used in this PR lay the foundation for adding new HTTP-based email APIs such as Mailgun.
(Also, as a small tweak, I've added the `node` executable to the npm test script since Windows doesn't support specifying interpreters with the …
=> Add support for E2E testing of HTTP mailers

.github/workflows/build.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, docs/build.md, src/bridges/email.rs, src/bridges/oidc.rs, src/config/mod.rs, src/utils/keys.rs, src/utils/real_ip.rs, src/utils/redis/locking.rs, src/web.rs
Some of our deps required Rust 1.42, plus we now use `matches!` ourselves, so the minimum version was bumped.
I've also re-enabled clippy and fixed some new errors that were generated.
=> Upgrade dependencies, clippy fixes, add caching to CI

Cargo.lock, Cargo.toml, src/utils/redis/pubsub.rs
`redis` v0.17.0 [added support for Redis 6 auth](https://github.com/mitsuhiko/redis-rs/blob/master/CHANGELOG.md#0170---2020-07-29), which many hosted Redis providers are now offering. The main feature of Redis 6 that portier is currently incompatible with is username/password auth.
This PR bumps the `redis` crate's version to the oldest version with support for Redis 6 auth. Versions v0.18 and v0.19 contain larger changes (including an upgrade to tokio v1), so I wanted to keep this update as small as possible since my Rust skills aren't that great.
Upgrading required a few changes:
1. `parse_redis_value_async` now expects a decoder as the first argument. In `redis`, this decoder comes from the `combine` crate, so that's been added as a dependency.
2. v0.17.0 also supports TLS connections, …
=> Bump redis crate to v0.17.0

.github/workflows/build.yml, .github/workflows/release.yml, release.sh
The release helper is from the discussion in #226. I tested the script up to (and except) the `git push` and `gh release create` lines.
=> Add release helper, disable cache on CI

.github/workflows/build.yml, Cargo.lock, Cargo.toml, src/handlers/auth.rs, src/utils/agent.rs, src/utils/delay_queue_task.rs, src/utils/redis/locking.rs, src/utils/redis/pubsub.rs
With this PR, all deps are now fully up-to-date. 🎉 
Had to bump the minimum Rust version to 1.44 for Tokio.
=> Upgrade all deps to Tokio v1

src/main.rs, src/validation.rs
portier fails to build with Rust 1.51, bombing out with:
```
error: panic message is not a string literal
--> src/main.rs:114:42
|
114 |             .unwrap_or_else(|err| panic!(format!("failed to build configuration: {}", err))),
|                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
note: the lint level is defined here
--> src/main.rs:1:9
|
1   | #![deny(warnings, clippy::pedantic)]
|         ^^^^^^^^
= note: `#[deny(non_fmt_panic)]` implied by `#[deny(warnings)]`
= note: this is no longer accepted in Rust 2021
= note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
error: panic message is not a string literal
--> src/main.rs:186:38
|
186 |         .unwrap_or_else(|err| panic!(format!("failed to …
```
=> resolve "error: panic message is not a string literal" errors

src/agents/key_manager/rotating.rs, src/error.rs
There are some more left, but I believe fixing those would break on Rust 1.46, which is our current minimum version.
=> Fix some clippy warnings

.github/actions/prep-linux-cross/action.yml, .github/actions/prep-linux-cross/main.js, .github/workflows/build.yml, .github/workflows/release.yml, Dockerfile
I got a mail saying Docker autobuilds are going away, so we need to build and push from somewhere else, naturally GitHub Actions. I took the opportunity to work on improving the release scripts. This now builds for a larger set of platforms. The full set is now:
- Linux: ARMv6, ARMv7, ARM64 (v8), Intel 32-bit & 64-bit
- Windows: Intel 32-bit & 64-bit
- macOS: Apple Silicon, Intel 64-bit
See a test release here: https://github.com/portier/portier-broker/releases/tag/v0.4.0-test
This also pushes the Linux builds as a multiarch Docker image to Docker Hub. See the test release: https://hub.docker.com/repository/registry-1.docker.io/portier/broker/tags?name=v0.4.0-test
Here's the CI run of the test release: https://github.com/portier/portier-broker/actions/runs/931453513
=> Build releases for more platforms, multiarch Docker images

Cargo.lock, Cargo.toml, src/agents/fetch.rs, src/agents/mailer/lettre_sendmail.rs, src/agents/mailer/lettre_smtp.rs, src/agents/mailer/mailgun.rs, src/agents/mailer/mod.rs, src/agents/mailer/postmark.rs, src/agents/store/memory.rs, src/agents/store/mod.rs, src/agents/store/redis.rs, src/agents/store/rusqlite.rs, src/bridges/email.rs, src/bridges/oidc.rs, src/handlers/auth.rs, src/handlers/pages.rs, src/main.rs, src/metrics.rs, src/router.rs, src/utils/domain_validator.rs, src/web.rs, src/webfinger.rs
This adds a Prometheus-compatible `GET /metrics` route. I specifically tried to add visibility into:
- Rate-limited requests
- Domain validation failures (because these now use actual DNS resolution)
- Latency of external calls (email / webfinger / oidc)
These metrics are public, so I've not used any identifying information.
=> Add Prometheus-compatible metrics

docs/key-management.md, src/agents/key_manager/manual.rs, src/agents/key_manager/mod.rs, src/agents/key_manager/rotating.rs, src/agents/store/memory.rs, src/agents/store/mod.rs, src/agents/store/redis.rs, src/agents/store/rusqlite.rs, src/bridges/email.rs, src/bridges/mod.rs, src/bridges/oidc.rs, src/config/mod.rs, src/handlers/auth.rs, src/handlers/token.rs, src/main.rs, src/utils/keys.rs, src/utils/pem.rs, src/web.rs
This PR adds the ability to import and export the full set of private keys in the broker store. Useful for migrating stores.
```bash
$ portier-broker ./config.toml --export-keys x.pem
Exported 5 private keys
```
```bash
$ portier-broker ./config.toml --import-keys x.pem
#1: found RS256 key, fingerprint: SHA256:rTStB2BTzS1H183n41gMXGgFzT7plSx82A4vuOckkqw= (as current, expires in 86400s)
#2: found RS256 key, fingerprint: SHA256:9YIZCzmAd4UodkMhwLIv9Ij3z0fI4Dc7LTcPFQBdbFQ= (as next, expires in 172800s)
#3: found RS256 key, fingerprint: SHA256:EACAs0O+PlDhyT1zPOUfEKtl35TseE76TrRmkKEVMGg= (as previous)
#4: found EdDSA key, fingerprint: SHA256:D1YK+5q+wsy3rjlwb2jvdCoCASz6+ay7U/gboMlXMNk= (as current, expires in 86400s)
#5: found EdDSA key, fingerprint: …
```
=> Keys import / export

contrib/gcp/.gitignore, contrib/gcp/README.md, contrib/gcp/portier.jinja, contrib/gcp/portier.jinja.schema, contrib/gcp/portier.yaml.dist
**WARNING:** Work in Progress, do not merge.
Some client work I was doing including making Portier deployable to GCP so I took the opportunity to generalise the solution so that others should be able to use it too. The deployment is described in the documentation in my branch at https://github.com/jimdigriz/portier-broker/tree/gcp/contrib/gcp and includes a list of issues/limitations; unlikely to be solved by myself as most require a Rust coder to work on the actual broker.
Probably of most interest to the project is the [(non-awful) conditional build](https://stackoverflow.com/a/54245466) feature slipped into the `Dockerfile` that lets the user deploy a non-forked version of the project in their environment and pull in the data directory as an externally sourced tarball from an HTTP …
=> [RFC|WIP] deploy to GCP

.github/workflows/daily.yml
Instead of running `cargo audit` on the `main` branch, this runs it against the latest release. I want to try prevent that automatic updates of stuff on `main` causes us to miss issues with dependencies in our current release binaries.
I had to fork actions-rs stuff, because the maintainer is currently unavailable. Specifically, I added an option to skip `cargo generate-lockfile`, because I believe that updates dependency versions in the lockfile. That's exactly what we don't want, because we want to check dependency versions as used in the release binaries.
=> Audit latest release daily

Cargo.lock, Cargo.toml, src/agents/mailer/mod.rs, src/email_address.rs
This adds validation using the `email_address` crate, which is what Lettre uses. This is on top of our existing validation. The crate has some additional checks that we don't do, like length checks on the local part and the domain part. Some of the simpler checks do overlap, so we delegate those now.
I suspect we were running into these missing checks later on when sending mail, based on reports from @tschaume. But at that point, we `.expect()` and crash.
In addition, it looks like we were converting our `EmailAddress` to Lettres`Mailbox` when sending, which also allows full name in the input string. We now instead convert to `Address`, hopefully eliminating any potential issues there.
=> Improve email parsing for Lettre compatibility

.envrc, .github/dependabot.yml, .github/workflows/daily.yml, .github/workflows/upgrade_deps.yml, .gitignore, flake.lock, flake.nix, src/main.rs
These all don't really touch broker functionality.
- I'd like to switch our own server in public-infra to use flakes at some point, and I believe we can ditch a bunch of custom code if we just package this repo as a flake too.
- We already require no `unsafe` in the broker code, might as well enforce it with a `#[forbid(...)]`.
- The [peter-evans/enable-pull-request-automerge](https://github.com/peter-evans/enable-pull-request-automerge) action is no longer necessary. See the readme there.
- We don't really have to do automatic upgrades as frequently as we do. Cargo updates are almost everyday, and I'm adding Nix in this PR, which is almost guaranteed daily, which is a lot of churn. It also doesn't really help with the security check anymore, because that checks the latest release, not …
=> Various non-code changes

.github/workflows/upgrade_deps.yml, docs/systemd/portier-broker.socket, src/main.rs, src/utils/real_ip.rs, src/web.rs
This does a little more work in `start_server` that was previously done in Hyper, namely accepting connections. But I believe Hyper 1.0 will remove connection handling, so this is something we'd have to do any way.
=> Support Unix sockets via socket activation

res/static/confirm_email.js, res/static/login_hint.js, src/handlers/auth.rs, tmpl/confirm_email.mustache, tmpl/login_hint.mustache
There are occasions where you want to provide `login_hint` but not have Portier auto submit the request and start the authentication for you.
My scenario is:
* use Portier as the login landing page
* application wants to auto-fill in the email address field with the last used email address
* user has multiple hats (email addresses and thus authorised for different things) at an organisation so may wish to use a different one than they did last time
This PR does the following:
1. make all parameters passed prepended with `_` (underscore) for private use by Portier
2. if `_login_hint` is set, this is displayed in the `<input name="login_hint" ...>` form field
* ~~annoyingly we cannot automatically move the cursor to the end without JS (and amending the HTML documents CSP) but I am okay with …
=> Support `_login_hint` to actually provide a hint

src/bridges/mod.rs, src/bridges/oidc.rs, src/crypto.rs, src/error.rs, src/handlers/auth.rs, src/handlers/token.rs, src/main.rs, src/web.rs
This PR improves our score on OIDC self-certification for `oidcc-basic-certification-test-plan`. Full compliance may be outside the scope of the broker, up for discussion. IMO, it seems like we'd have to add a bunch of complexity for little benefit.
Where we still fail:
- We don't implement userinfo, and the entire test suite depends on it, despite it being optional. Fundamental is that we don't have access tokens at all, so we'd have to add storage for those if we want to do that. I've been cheating the test by doing 'access token = email', but that doesn't sound smart for production. It gives an illusion our 'access tokens' / sessions are permanently valid (and there are other tests in the test suite we'd fail any way.)
- We partially fail `oidcc-prompt-none-logged-in`. We forward …
=> Improve compliance with OIDC spec

.github/workflows/build.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, flake.nix, src/agents/fetch.rs, src/agents/mailer/mailgun.rs, src/agents/mailer/postmark.rs, src/agents/store/memory.rs, src/agents/store/redis.rs, src/agents/store/rusqlite.rs, src/config/env.rs, src/config/mod.rs, src/handlers/normalize.rs, src/handlers/pages.rs, src/main.rs, src/web.rs
Biggest changes here are:
- Hyper no longer provides a Body struct, but a Body trait, so this adds an implementation of that.
- Now using the 'reqwest' crate for HTTP client stuff.
=> Upgrade to Hyper 1.0

Cargo.lock, Cargo.toml, src/agents/fetch.rs, src/agents/store/mod.rs, src/handlers/pages.rs, src/metrics.rs
The prometheus crate wasn't heavy, but this gives us a little more control over the output. Specifically, 0 stats were missing, plus we get control over order.
=> Drop prometheus crate dep, reimplement metrics

Cargo.lock, Cargo.toml, src/config/env.rs, src/config/mod.rs, src/config/toml.rs, src/utils/keys.rs, src/utils/rng.rs
Since we switched from Ring to AWS Libcrypto, following Rustls, we already have a lib capable of generating RSA keys, and no longer have a use for the rust-crypto `rsa` crate.
We can probably remove the 'external command' method of generating RSA keys in the near feature, and move key size parsing to the config modules, so it is caught during startup.
=> Use AWS Libcrypto to generate RSA keys

Cargo.toml, src/agents/key_manager/manual.rs, src/agents/key_manager/rotating.rs, src/crypto.rs, src/utils/keys.rs, src/utils/pem.rs, src/utils/rng.rs
This simply removes the `ring` alias, and instead uses `aws-lc-rs` directly.
=> Remove ring alias

src/agents/mailer/mailgun.rs, src/agents/mailer/mod.rs, src/agents/mailer/postmark.rs, src/agents/mailer/sendgrid.rs
We added `List-Id` in the past, but it appears MS Exchange ignores this and instead looks for `X-Auto-Response-Suppress`. This PR adds that header.
=> Suppress auto responses from MS Exchange

contrib/gcp/README.md, contrib/gcp/portier.jinja, contrib/gcp/portier.jinja.schema
Another week, another product in the Google Graveyard, this time it is Container Registry. One of the commits in this PR migrates to Artifact Registry...probably will be here again next week as that is set to be phased out too...</rant> :-/
The other commit is in response to O365 sucking in other ways too, turns out their name servers are unreliable and *often* fail to return A/AAAA records so we make `public_ip` configurable in the deployment template; correcting what it always should have been.
=> Fixes to the contributed GCP deployment

Cargo.lock, Cargo.toml, src/agents/store/redis.rs, src/utils/redis/locking.rs, src/utils/redis/pubsub.rs
This finally upgrades the `redis` crate and relies on its support for pubsub, instead of our own solution. We do now require RESP3, which means Redis >= 6.0 (or valkey), which is more than 4 years old by now.
=> Upgrade Redis, use RESP3 for pubsub

Dockerfile, contrib/gcp/portier.jinja, contrib/gcp/portier.jinja.schema, src/web.rs
Missing functionality from the PR #996, where when `allowed_origins` is unset, the CORS headers should be sent too.
Also a commit to fix the Dockerfile (cannot build when you got no source code); looks like just a line missed being trimmed.
=> fix CORS support edge case

src/web.rs
If you have multiple RPs using the same Portier instance via a SPA then the caching on `/.well-known/openid-configuration` (and others) causes problems as within the period another site will see CORS headers allowing the other site and not its-self.
To resolve this we needs `vary: origin` to be included to instruct the browser cache to partition by `origin`.
=> for CORS include 'vary: origin' to avoid CORS errors between two RPs

config.toml.dist, contrib/gcp/portier.jinja, contrib/gcp/portier.jinja.schema, src/config/env.rs, src/config/mod.rs, src/config/toml.rs, src/web.rs
This PR allows the user to optionally customise the Content-Security-Policy header to loosen the restrictions currently in place, for example to set `font-src: 'self'`.
=> allow Content-Security-Policy response header to be customized
